#3 switched run back to multi with |

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -18,5 +18,6 @@ jobs:
           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MVOGELGESANG }}'
           projectId: mvogelgesang
       - name: lighthouse CI
-        run: npm install -g @lhci/cli@0.3.x
-        run: lhci autorun --upload.target=temporary-public-storage --serverBaseUrl=${{steps.firebase_output.outputs.urls}} || echo "LHCI failed!"
+        run: |
+         npm install -g @lhci/cli@0.3.x
+         lhci autorun --upload.target=temporary-public-storage --serverBaseUrl=${{steps.firebase_output.outputs.urls}} || echo "LHCI failed!"
